apiVersion: v1
description: "A Helm chart for Activiti Cloud GraphQL Notifications"
icon: "https://salaboy.files.wordpress.com/2018/01/acitiviti_icon_fullcolor_github_400x400.png"
name: activiti-cloud-query-graphql-notifications
version: 1.0.2
